spring:
  application:
    name: SportTimerSyncServer

  datasource:
    url: jdbc:sqlite:sport_timer_sync_server.db
  jpa:
    show-sql: true

  liquibase:
    enabled: true
    drop-first: false

springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080